
name: WebDriver Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    # - run: docker run -d --net=host --shm-size=2g selenium/standalone-chrome:latest
    
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: beta
      id: setup-chrome
    - run:
       chrome --version
    
    - name: Install Dependencies
      run: npm install
    
    - name: Start a server
      run: npx selenium-standalone start
    
    - name: Run tests
      run: npx codeceptjs run --debug
      
    env:
        CI: true
